bus_stops = {
    "L201B": [
        "zerdal",
        "lycee bouknadel",
        "gare bouknadel",
        "hopital bouknadel",
        "com. bouknadel",
        "entre bouknadel",
        "res halima",
        "doha",
        "qantra",
        "ex police bouknadel",
        "ecole taha hesseine",
        "rond point ihsan",
        "avenue d",
        "super",
        "dar al hamra",
        "tramway hay karima",
        "houlyoud",
        "souq assalihin",
        "chateau hay salam",
    ],
}